onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - swup

overrides:
  '@swup/plugin': '>=4.0.0'

patchedDependencies:
  midori-bg@1.0.3: patches/midori-bg@1.0.3.patch
