name: Code quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 10.14.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Run Prettier check
        run: pnpm exec prettier --check "src/**/*.{js,ts,jsx,tsx,json,css,md}"

      - name: Run oxlint
        run: pnpm exec oxlint --strict ./src
