name: Code quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier check
        run: npx prettier --check "src/**/*.{js,ts,jsx,tsx,json,css,md}"

      - name: Run oxlint
        run: npx oxlint --strict ./src